/**
 * Seed catalogue: enough Push / Pull / Legs machine exercises to demonstrate
 * the product. Extend by adding rows — no code changes needed.
 *
 * Muscle roles follow common exercise-science descriptions (prime movers =
 * primary, meaningful synergists = secondary). They are qualitative on
 * purpose; no activation percentages are claimed.
 */

import { CatalogueData, ContributionRole, ExerciseMuscleContribution } from './types';

const P = (...ids: string[]): ExerciseMuscleContribution[] => ids.map((muscleId) => ({ muscleId, role: 'primary' as ContributionRole }));
const S = (...ids: string[]): ExerciseMuscleContribution[] => ids.map((muscleId) => ({ muscleId, role: 'secondary' as ContributionRole }));

export const CATALOGUE: CatalogueData = {
  version: 'cat-1',
  bodyRegions: [
    { id: 'chest', name: 'Chest' },
    { id: 'back', name: 'Back' },
    { id: 'shoulders', name: 'Shoulders' },
    { id: 'arms', name: 'Arms' },
    { id: 'legs', name: 'Legs' },
  ],
  muscles: [
    { id: 'pec_major_sternal', name: 'Pectoralis major (sternal / mid-lower chest)' },
    { id: 'pec_major_clavicular', name: 'Pectoralis major (clavicular / upper chest)' },
    { id: 'anterior_deltoid', name: 'Anterior deltoid' },
    { id: 'lateral_deltoid', name: 'Lateral deltoid' },
    { id: 'posterior_deltoid', name: 'Posterior deltoid' },
    { id: 'triceps', name: 'Triceps brachii' },
    { id: 'biceps', name: 'Biceps brachii' },
    { id: 'brachialis', name: 'Brachialis' },
    { id: 'brachioradialis', name: 'Brachioradialis' },
    { id: 'latissimus', name: 'Latissimus dorsi' },
    { id: 'teres_major', name: 'Teres major' },
    { id: 'rhomboids', name: 'Rhomboids' },
    { id: 'mid_trapezius', name: 'Middle trapezius' },
    { id: 'lower_trapezius', name: 'Lower trapezius' },
    { id: 'upper_trapezius', name: 'Upper trapezius' },
    { id: 'erector_spinae', name: 'Erector spinae' },
    { id: 'quadriceps', name: 'Quadriceps' },
    { id: 'gluteus_maximus', name: 'Gluteus maximus' },
    { id: 'gluteus_medius', name: 'Gluteus medius / minimus' },
    { id: 'hamstrings', name: 'Hamstrings' },
    { id: 'adductors', name: 'Adductors' },
    { id: 'gastrocnemius', name: 'Gastrocnemius' },
  ],
  equipment: [
    { id: 'lat_pulldown_machine', name: 'Lat pulldown machine', hasWeightStack: true },
    { id: 'seated_row_machine', name: 'Seated row machine (chest pad)', hasWeightStack: true },
    { id: 'cable_station', name: 'Cable station (adjustable pulley)', hasWeightStack: true },
    { id: 'chest_press_machine', name: 'Seated chest press machine', hasWeightStack: true },
    { id: 'incline_press_machine', name: 'Incline chest press machine', hasWeightStack: true },
    { id: 'pec_deck', name: 'Pec deck / rear-delt fly machine', hasWeightStack: true },
    { id: 'shoulder_press_machine', name: 'Shoulder press machine', hasWeightStack: true },
    { id: 'lateral_raise_machine', name: 'Lateral raise machine', hasWeightStack: true },
    { id: 'biceps_curl_machine', name: 'Biceps curl machine (preacher)', hasWeightStack: true },
    { id: 'leg_press_machine', name: 'Seated leg press (selectorized)', hasWeightStack: true },
    { id: 'leg_extension_machine', name: 'Leg extension machine', hasWeightStack: true },
    { id: 'seated_leg_curl_machine', name: 'Seated leg curl machine', hasWeightStack: true },
    { id: 'lying_leg_curl_machine', name: 'Lying leg curl machine', hasWeightStack: true },
    { id: 'hip_abduction_machine', name: 'Hip abduction machine', hasWeightStack: true },
  ],
  exercises: [
    { id: 'lat_pulldown', name: 'Lat Pulldown', movementPattern: 'Pull', bodyRegionIds: ['back'] },
    { id: 'seated_row', name: 'Seated Row', movementPattern: 'Pull', bodyRegionIds: ['back'] },
    { id: 'reverse_fly', name: 'Reverse Fly (rear delt)', movementPattern: 'Pull', bodyRegionIds: ['shoulders', 'back'] },
    { id: 'biceps_curl', name: 'Biceps Curl', movementPattern: 'Pull', bodyRegionIds: ['arms'] },
    { id: 'chest_press', name: 'Chest Press', movementPattern: 'Push', bodyRegionIds: ['chest'] },
    { id: 'chest_fly', name: 'Chest Fly', movementPattern: 'Push', bodyRegionIds: ['chest'] },
    { id: 'shoulder_press', name: 'Shoulder Press', movementPattern: 'Push', bodyRegionIds: ['shoulders'] },
    { id: 'lateral_raise', name: 'Lateral Raise', movementPattern: 'Push', bodyRegionIds: ['shoulders'] },
    { id: 'triceps_pushdown', name: 'Triceps Pushdown', movementPattern: 'Push', bodyRegionIds: ['arms'] },
    { id: 'leg_press', name: 'Leg Press', movementPattern: 'Legs', bodyRegionIds: ['legs'] },
    { id: 'leg_extension', name: 'Leg Extension', movementPattern: 'Legs', bodyRegionIds: ['legs'] },
    { id: 'leg_curl', name: 'Leg Curl', movementPattern: 'Legs', bodyRegionIds: ['legs'] },
    { id: 'hip_abduction', name: 'Hip Abduction', movementPattern: 'Legs', bodyRegionIds: ['legs'] },
  ],
  variants: [
    // ---- Pull ----
    {
      id: 'lat_pulldown.machine.wide_overhand',
      exerciseId: 'lat_pulldown',
      equipmentId: 'lat_pulldown_machine',
      variantName: 'Wide overhand grip',
      contributions: [...P('latissimus'), ...S('teres_major', 'rhomboids', 'lower_trapezius', 'mid_trapezius', 'posterior_deltoid', 'biceps', 'brachialis')],
    },
    {
      id: 'lat_pulldown.machine.close_neutral',
      exerciseId: 'lat_pulldown',
      equipmentId: 'lat_pulldown_machine',
      variantName: 'Close neutral grip',
      contributions: [...P('latissimus'), ...S('teres_major', 'rhomboids', 'lower_trapezius', 'biceps', 'brachialis', 'brachioradialis')],
    },
    {
      id: 'lat_pulldown.machine.underhand',
      exerciseId: 'lat_pulldown',
      equipmentId: 'lat_pulldown_machine',
      variantName: 'Underhand (supinated) grip',
      contributions: [...P('latissimus'), ...S('biceps', 'teres_major', 'brachialis', 'rhomboids', 'lower_trapezius')],
    },
    {
      id: 'seated_row.machine.neutral',
      exerciseId: 'seated_row',
      equipmentId: 'seated_row_machine',
      variantName: 'Neutral grip',
      contributions: [...P('latissimus', 'rhomboids', 'mid_trapezius'), ...S('teres_major', 'posterior_deltoid', 'biceps', 'brachialis')],
    },
    {
      id: 'seated_row.machine.wide_overhand',
      exerciseId: 'seated_row',
      equipmentId: 'seated_row_machine',
      variantName: 'Wide overhand grip (elbows out)',
      contributions: [...P('rhomboids', 'mid_trapezius', 'posterior_deltoid'), ...S('latissimus', 'teres_major', 'biceps', 'brachialis')],
    },
    {
      id: 'seated_row.cable.close_neutral',
      exerciseId: 'seated_row',
      equipmentId: 'cable_station',
      variantName: 'Low pulley, close neutral handle',
      contributions: [...P('latissimus', 'rhomboids', 'mid_trapezius'), ...S('teres_major', 'posterior_deltoid', 'biceps', 'brachialis', 'erector_spinae')],
    },
    {
      id: 'reverse_fly.pec_deck',
      exerciseId: 'reverse_fly',
      equipmentId: 'pec_deck',
      variantName: null,
      contributions: [...P('posterior_deltoid'), ...S('mid_trapezius', 'rhomboids')],
    },
    {
      id: 'biceps_curl.machine.supinated',
      exerciseId: 'biceps_curl',
      equipmentId: 'biceps_curl_machine',
      variantName: null,
      contributions: [...P('biceps'), ...S('brachialis', 'brachioradialis')],
    },
    {
      id: 'biceps_curl.cable.straight_bar',
      exerciseId: 'biceps_curl',
      equipmentId: 'cable_station',
      variantName: 'Low pulley, straight bar (supinated)',
      contributions: [...P('biceps'), ...S('brachialis', 'brachioradialis')],
    },
    {
      id: 'biceps_curl.cable.rope_hammer',
      exerciseId: 'biceps_curl',
      equipmentId: 'cable_station',
      variantName: 'Low pulley, rope (hammer / neutral)',
      contributions: [...P('brachialis', 'brachioradialis'), ...S('biceps')],
    },
    // ---- Push ----
    {
      id: 'chest_press.machine',
      exerciseId: 'chest_press',
      equipmentId: 'chest_press_machine',
      variantName: null,
      contributions: [...P('pec_major_sternal'), ...S('pec_major_clavicular', 'anterior_deltoid', 'triceps')],
    },
    {
      id: 'chest_press.incline_machine',
      exerciseId: 'chest_press',
      equipmentId: 'incline_press_machine',
      variantName: null,
      contributions: [...P('pec_major_clavicular'), ...S('anterior_deltoid', 'pec_major_sternal', 'triceps')],
    },
    {
      id: 'chest_fly.pec_deck',
      exerciseId: 'chest_fly',
      equipmentId: 'pec_deck',
      variantName: null,
      contributions: [...P('pec_major_sternal'), ...S('pec_major_clavicular', 'anterior_deltoid')],
    },
    {
      id: 'shoulder_press.machine.pronated',
      exerciseId: 'shoulder_press',
      equipmentId: 'shoulder_press_machine',
      variantName: 'Overhand grip',
      contributions: [...P('anterior_deltoid'), ...S('lateral_deltoid', 'triceps', 'upper_trapezius', 'pec_major_clavicular')],
    },
    {
      id: 'shoulder_press.machine.neutral',
      exerciseId: 'shoulder_press',
      equipmentId: 'shoulder_press_machine',
      variantName: 'Neutral grip',
      contributions: [...P('anterior_deltoid'), ...S('triceps', 'lateral_deltoid', 'upper_trapezius', 'pec_major_clavicular')],
    },
    {
      id: 'lateral_raise.machine',
      exerciseId: 'lateral_raise',
      equipmentId: 'lateral_raise_machine',
      variantName: null,
      contributions: [...P('lateral_deltoid'), ...S('anterior_deltoid', 'upper_trapezius')],
    },
    {
      id: 'triceps_pushdown.cable.straight_bar',
      exerciseId: 'triceps_pushdown',
      equipmentId: 'cable_station',
      variantName: 'High pulley, straight bar',
      contributions: [...P('triceps')],
    },
    {
      id: 'triceps_pushdown.cable.rope',
      exerciseId: 'triceps_pushdown',
      equipmentId: 'cable_station',
      variantName: 'High pulley, rope',
      contributions: [...P('triceps')],
    },
    // ---- Legs ----
    {
      id: 'leg_press.machine.standard',
      exerciseId: 'leg_press',
      equipmentId: 'leg_press_machine',
      variantName: 'Feet mid-platform, hip width',
      contributions: [...P('quadriceps'), ...S('gluteus_maximus', 'adductors')],
    },
    {
      id: 'leg_press.machine.high_wide',
      exerciseId: 'leg_press',
      equipmentId: 'leg_press_machine',
      variantName: 'Feet high and wide',
      contributions: [...P('gluteus_maximus', 'quadriceps'), ...S('adductors', 'hamstrings')],
    },
    {
      id: 'leg_extension.machine',
      exerciseId: 'leg_extension',
      equipmentId: 'leg_extension_machine',
      variantName: null,
      contributions: [...P('quadriceps')],
    },
    {
      id: 'leg_curl.seated',
      exerciseId: 'leg_curl',
      equipmentId: 'seated_leg_curl_machine',
      variantName: null,
      contributions: [...P('hamstrings'), ...S('gastrocnemius')],
    },
    {
      id: 'leg_curl.lying',
      exerciseId: 'leg_curl',
      equipmentId: 'lying_leg_curl_machine',
      variantName: null,
      contributions: [...P('hamstrings'), ...S('gastrocnemius')],
    },
    {
      id: 'hip_abduction.machine',
      exerciseId: 'hip_abduction',
      equipmentId: 'hip_abduction_machine',
      variantName: null,
      contributions: [...P('gluteus_medius'), ...S('gluteus_maximus')],
    },
  ],
};
